# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.9
#
# <auto-generated>
#
# Generated from file `iot.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module IoT
_M_IoT = Ice.openModule('IoT')
__name__ = 'IoT'

if 'ValueOutOfRangeException' not in _M_IoT.__dict__:
    _M_IoT.ValueOutOfRangeException = Ice.createTempClass()
    class ValueOutOfRangeException(Ice.UserException):
        def __init__(self, reason=''):
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::IoT::ValueOutOfRangeException'

    _M_IoT._t_ValueOutOfRangeException = IcePy.defineException('::IoT::ValueOutOfRangeException', ValueOutOfRangeException, (), False, None, (('reason', (), IcePy._t_string, False, 0),))
    ValueOutOfRangeException._ice_type = _M_IoT._t_ValueOutOfRangeException

    _M_IoT.ValueOutOfRangeException = ValueOutOfRangeException
    del ValueOutOfRangeException

if 'UnknownSettingException' not in _M_IoT.__dict__:
    _M_IoT.UnknownSettingException = Ice.createTempClass()
    class UnknownSettingException(Ice.UserException):
        def __init__(self, reason=''):
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::IoT::UnknownSettingException'

    _M_IoT._t_UnknownSettingException = IcePy.defineException('::IoT::UnknownSettingException', UnknownSettingException, (), False, None, (('reason', (), IcePy._t_string, False, 0),))
    UnknownSettingException._ice_type = _M_IoT._t_UnknownSettingException

    _M_IoT.UnknownSettingException = UnknownSettingException
    del UnknownSettingException

if 'UnsupportedBeverageTypeException' not in _M_IoT.__dict__:
    _M_IoT.UnsupportedBeverageTypeException = Ice.createTempClass()
    class UnsupportedBeverageTypeException(Ice.UserException):
        def __init__(self, reason=''):
            self.reason = reason

        def __str__(self):
            return IcePy.stringifyException(self)

        __repr__ = __str__

        _ice_id = '::IoT::UnsupportedBeverageTypeException'

    _M_IoT._t_UnsupportedBeverageTypeException = IcePy.defineException('::IoT::UnsupportedBeverageTypeException', UnsupportedBeverageTypeException, (), False, None, (('reason', (), IcePy._t_string, False, 0),))
    UnsupportedBeverageTypeException._ice_type = _M_IoT._t_UnsupportedBeverageTypeException

    _M_IoT.UnsupportedBeverageTypeException = UnsupportedBeverageTypeException
    del UnsupportedBeverageTypeException

if '_t_DeviceInfo' not in _M_IoT.__dict__:
    _M_IoT._t_DeviceInfo = IcePy.defineDictionary('::IoT::DeviceInfo', (), IcePy._t_string, IcePy._t_string)

if '_t_Settings' not in _M_IoT.__dict__:
    _M_IoT._t_Settings = IcePy.defineDictionary('::IoT::Settings', (), IcePy._t_string, IcePy._t_string)

if 'IoTDevice' not in _M_IoT.__dict__:
    _M_IoT.IoTDevice = Ice.createTempClass()
    class IoTDevice(Ice.Value):
        def __init__(self, name='', brand='', model='', type=''):
            self.name = name
            self.brand = brand
            self.model = model
            self.type = type

        def ice_id(self):
            return '::IoT::IoTDevice'

        @staticmethod
        def ice_staticId():
            return '::IoT::IoTDevice'

        def __str__(self):
            return IcePy.stringify(self, _M_IoT._t_IoTDevice)

        __repr__ = __str__

    _M_IoT._t_IoTDevice = IcePy.defineValue('::IoT::IoTDevice', IoTDevice, -1, (), False, False, None, (
        ('name', (), IcePy._t_string, False, 0),
        ('brand', (), IcePy._t_string, False, 0),
        ('model', (), IcePy._t_string, False, 0),
        ('type', (), IcePy._t_string, False, 0)
    ))
    IoTDevice._ice_type = _M_IoT._t_IoTDevice

    _M_IoT.IoTDevice = IoTDevice
    del IoTDevice

_M_IoT._t_IoTDeviceOperation = IcePy.defineValue('::IoT::IoTDeviceOperation', Ice.Value, -1, (), False, True, None, ())

if 'IoTDeviceOperationPrx' not in _M_IoT.__dict__:
    _M_IoT.IoTDeviceOperationPrx = Ice.createTempClass()
    class IoTDeviceOperationPrx(Ice.ObjectPrx):

        def getInfo(self, context=None):
            return _M_IoT.IoTDeviceOperation._op_getInfo.invoke(self, ((), context))

        def getInfoAsync(self, context=None):
            return _M_IoT.IoTDeviceOperation._op_getInfo.invokeAsync(self, ((), context))

        def begin_getInfo(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_IoT.IoTDeviceOperation._op_getInfo.begin(self, ((), _response, _ex, _sent, context))

        def end_getInfo(self, _r):
            return _M_IoT.IoTDeviceOperation._op_getInfo.end(self, _r)

        def changeSettings(self, settings, context=None):
            return _M_IoT.IoTDeviceOperation._op_changeSettings.invoke(self, ((settings, ), context))

        def changeSettingsAsync(self, settings, context=None):
            return _M_IoT.IoTDeviceOperation._op_changeSettings.invokeAsync(self, ((settings, ), context))

        def begin_changeSettings(self, settings, _response=None, _ex=None, _sent=None, context=None):
            return _M_IoT.IoTDeviceOperation._op_changeSettings.begin(self, ((settings, ), _response, _ex, _sent, context))

        def end_changeSettings(self, _r):
            return _M_IoT.IoTDeviceOperation._op_changeSettings.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IoT.IoTDeviceOperationPrx.ice_checkedCast(proxy, '::IoT::IoTDeviceOperation', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IoT.IoTDeviceOperationPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IoT::IoTDeviceOperation'
    _M_IoT._t_IoTDeviceOperationPrx = IcePy.defineProxy('::IoT::IoTDeviceOperation', IoTDeviceOperationPrx)

    _M_IoT.IoTDeviceOperationPrx = IoTDeviceOperationPrx
    del IoTDeviceOperationPrx

    _M_IoT.IoTDeviceOperation = Ice.createTempClass()
    class IoTDeviceOperation(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IoT::IoTDeviceOperation')

        def ice_id(self, current=None):
            return '::IoT::IoTDeviceOperation'

        @staticmethod
        def ice_staticId():
            return '::IoT::IoTDeviceOperation'

        def getInfo(self, current=None):
            raise NotImplementedError("servant method 'getInfo' not implemented")

        def changeSettings(self, settings, current=None):
            raise NotImplementedError("servant method 'changeSettings' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IoT._t_IoTDeviceOperationDisp)

        __repr__ = __str__

    _M_IoT._t_IoTDeviceOperationDisp = IcePy.defineClass('::IoT::IoTDeviceOperation', IoTDeviceOperation, (), None, ())
    IoTDeviceOperation._ice_type = _M_IoT._t_IoTDeviceOperationDisp

    IoTDeviceOperation._op_getInfo = IcePy.Operation('getInfo', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (), (), ((), _M_IoT._t_DeviceInfo, False, 0), ())
    IoTDeviceOperation._op_changeSettings = IcePy.Operation('changeSettings', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, False, None, (), (((), _M_IoT._t_Settings, False, 0),), (), None, (_M_IoT._t_UnknownSettingException, _M_IoT._t_ValueOutOfRangeException))

    _M_IoT.IoTDeviceOperation = IoTDeviceOperation
    del IoTDeviceOperation

if 'BeverageType' not in _M_IoT.__dict__:
    _M_IoT.BeverageType = Ice.createTempClass()
    class BeverageType(Ice.EnumBase):

        def __init__(self, _n, _v):
            Ice.EnumBase.__init__(self, _n, _v)

        def valueOf(self, _n):
            if _n in self._enumerators:
                return self._enumerators[_n]
            return None
        valueOf = classmethod(valueOf)

    BeverageType.AMERICANO = BeverageType("AMERICANO", 0)
    BeverageType.CAPPUCCINO = BeverageType("CAPPUCCINO", 1)
    BeverageType.ESPRESSO = BeverageType("ESPRESSO", 2)
    BeverageType.CARAMELMACCHIATO = BeverageType("CARAMELMACCHIATO", 3)
    BeverageType.TEA = BeverageType("TEA", 4)
    BeverageType.HOTCHOCOLATE = BeverageType("HOTCHOCOLATE", 5)
    BeverageType.HOTMILK = BeverageType("HOTMILK", 6)
    BeverageType._enumerators = { 0:BeverageType.AMERICANO, 1:BeverageType.CAPPUCCINO, 2:BeverageType.ESPRESSO, 3:BeverageType.CARAMELMACCHIATO, 4:BeverageType.TEA, 5:BeverageType.HOTCHOCOLATE, 6:BeverageType.HOTMILK }

    _M_IoT._t_BeverageType = IcePy.defineEnum('::IoT::BeverageType', BeverageType, (), BeverageType._enumerators)

    _M_IoT.BeverageType = BeverageType
    del BeverageType

if '_t_AvailableBeverageTypes' not in _M_IoT.__dict__:
    _M_IoT._t_AvailableBeverageTypes = IcePy.defineSequence('::IoT::AvailableBeverageTypes', (), _M_IoT._t_BeverageType)

if 'BeverageOrder' not in _M_IoT.__dict__:
    _M_IoT.BeverageOrder = Ice.createTempClass()
    class BeverageOrder(Ice.Value):
        def __init__(self, beverageType=_M_IoT.BeverageType.AMERICANO, volume=0):
            self.beverageType = beverageType
            self.volume = volume

        def ice_id(self):
            return '::IoT::BeverageOrder'

        @staticmethod
        def ice_staticId():
            return '::IoT::BeverageOrder'

        def __str__(self):
            return IcePy.stringify(self, _M_IoT._t_BeverageOrder)

        __repr__ = __str__

    _M_IoT._t_BeverageOrder = IcePy.defineValue('::IoT::BeverageOrder', BeverageOrder, -1, (), False, False, None, (
        ('beverageType', (), _M_IoT._t_BeverageType, False, 0),
        ('volume', (), IcePy._t_short, False, 0)
    ))
    BeverageOrder._ice_type = _M_IoT._t_BeverageOrder

    _M_IoT.BeverageOrder = BeverageOrder
    del BeverageOrder

if '_t_BeverageOrders' not in _M_IoT.__dict__:
    _M_IoT._t_BeverageOrders = IcePy.defineSequence('::IoT::BeverageOrders', (), _M_IoT._t_BeverageOrder)

if 'Beverage' not in _M_IoT.__dict__:
    _M_IoT.Beverage = Ice.createTempClass()
    class Beverage(Ice.Value):
        def __init__(self, beverageType=_M_IoT.BeverageType.AMERICANO, volume=0):
            self.beverageType = beverageType
            self.volume = volume

        def ice_id(self):
            return '::IoT::Beverage'

        @staticmethod
        def ice_staticId():
            return '::IoT::Beverage'

        def __str__(self):
            return IcePy.stringify(self, _M_IoT._t_Beverage)

        __repr__ = __str__

    _M_IoT._t_Beverage = IcePy.defineValue('::IoT::Beverage', Beverage, -1, (), False, False, None, (
        ('beverageType', (), _M_IoT._t_BeverageType, False, 0),
        ('volume', (), IcePy._t_short, False, 0)
    ))
    Beverage._ice_type = _M_IoT._t_Beverage

    _M_IoT.Beverage = Beverage
    del Beverage

if '_t_Coffees' not in _M_IoT.__dict__:
    _M_IoT._t_Coffees = IcePy.defineSequence('::IoT::Coffees', (), _M_IoT._t_Beverage)

if 'CoffeeMaker' not in _M_IoT.__dict__:
    _M_IoT.CoffeeMaker = Ice.createTempClass()
    class CoffeeMaker(_M_IoT.IoTDevice):
        def __init__(self, name='', brand='', model='', type='', volume=0, beverageTypes=None):
            _M_IoT.IoTDevice.__init__(self, name, brand, model, type)
            self.volume = volume
            self.beverageTypes = beverageTypes

        def ice_id(self):
            return '::IoT::CoffeeMaker'

        @staticmethod
        def ice_staticId():
            return '::IoT::CoffeeMaker'

        def __str__(self):
            return IcePy.stringify(self, _M_IoT._t_CoffeeMaker)

        __repr__ = __str__

    _M_IoT._t_CoffeeMaker = IcePy.defineValue('::IoT::CoffeeMaker', CoffeeMaker, -1, (), False, False, _M_IoT._t_IoTDevice, (
        ('volume', (), IcePy._t_short, False, 0),
        ('beverageTypes', (), _M_IoT._t_AvailableBeverageTypes, False, 0)
    ))
    CoffeeMaker._ice_type = _M_IoT._t_CoffeeMaker

    _M_IoT.CoffeeMaker = CoffeeMaker
    del CoffeeMaker

_M_IoT._t_CoffeeMakerOperation = IcePy.defineValue('::IoT::CoffeeMakerOperation', Ice.Value, -1, (), False, True, None, ())

if 'CoffeeMakerOperationPrx' not in _M_IoT.__dict__:
    _M_IoT.CoffeeMakerOperationPrx = Ice.createTempClass()
    class CoffeeMakerOperationPrx(_M_IoT.IoTDeviceOperationPrx):

        def makeBeverage(self, beverageType, context=None):
            return _M_IoT.CoffeeMakerOperation._op_makeBeverage.invoke(self, ((beverageType, ), context))

        def makeBeverageAsync(self, beverageType, context=None):
            return _M_IoT.CoffeeMakerOperation._op_makeBeverage.invokeAsync(self, ((beverageType, ), context))

        def begin_makeBeverage(self, beverageType, _response=None, _ex=None, _sent=None, context=None):
            return _M_IoT.CoffeeMakerOperation._op_makeBeverage.begin(self, ((beverageType, ), _response, _ex, _sent, context))

        def end_makeBeverage(self, _r):
            return _M_IoT.CoffeeMakerOperation._op_makeBeverage.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_IoT.CoffeeMakerOperationPrx.ice_checkedCast(proxy, '::IoT::CoffeeMakerOperation', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_IoT.CoffeeMakerOperationPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::IoT::CoffeeMakerOperation'
    _M_IoT._t_CoffeeMakerOperationPrx = IcePy.defineProxy('::IoT::CoffeeMakerOperation', CoffeeMakerOperationPrx)

    _M_IoT.CoffeeMakerOperationPrx = CoffeeMakerOperationPrx
    del CoffeeMakerOperationPrx

    _M_IoT.CoffeeMakerOperation = Ice.createTempClass()
    class CoffeeMakerOperation(_M_IoT.IoTDeviceOperation):

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::IoT::CoffeeMakerOperation', '::IoT::IoTDeviceOperation')

        def ice_id(self, current=None):
            return '::IoT::CoffeeMakerOperation'

        @staticmethod
        def ice_staticId():
            return '::IoT::CoffeeMakerOperation'

        def makeBeverage(self, beverageType, current=None):
            raise NotImplementedError("servant method 'makeBeverage' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_IoT._t_CoffeeMakerOperationDisp)

        __repr__ = __str__

    _M_IoT._t_CoffeeMakerOperationDisp = IcePy.defineClass('::IoT::CoffeeMakerOperation', CoffeeMakerOperation, (), None, (_M_IoT._t_IoTDeviceOperationDisp,))
    CoffeeMakerOperation._ice_type = _M_IoT._t_CoffeeMakerOperationDisp

    CoffeeMakerOperation._op_makeBeverage = IcePy.Operation('makeBeverage', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), _M_IoT._t_BeverageType, False, 0),), (), ((), _M_IoT._t_Beverage, False, 0), (_M_IoT._t_UnsupportedBeverageTypeException,))

    _M_IoT.CoffeeMakerOperation = CoffeeMakerOperation
    del CoffeeMakerOperation

# End of module IoT
